# Generated by Django 6.0.3 on 2026-03-19 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Currency Code')),
                ('name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('flag', models.CharField(max_length=10, verbose_name='Flag Emoji')),
                ('buy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Buy Rate (SDG)')),
                ('sell_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Sell Rate (SDG)')),
                ('change_percent', models.CharField(default='+0.5%', max_length=10, verbose_name='Change %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('show_in_rates_table', models.BooleanField(default=True, verbose_name='Show in Rates Table')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='حول يا زول', max_length=100)),
                ('support_phone', models.CharField(default='+249920380318', max_length=20)),
                ('support_email', models.EmailField(default='anwraltahir@gmail.com', max_length=254)),
                ('whatsapp_link', models.URLField(default='https://wa.me/249920380318')),
                ('is_maintenance', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('account_name', models.CharField(max_length=100, verbose_name='Account Name')),
                ('is_active', models.BooleanField(default=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='api.currency')),
            ],
        ),
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sent', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Sent')),
                ('exchange_rate_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Rate at Time')),
                ('amount_to_receive_sdg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount to Receive (SDG)')),
                ('bankak_name', models.CharField(max_length=100, verbose_name='Bankak Recipient Name')),
                ('bankak_number', models.CharField(max_length=50, verbose_name='Bankak Account Number')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender Name')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Transfer Receipt')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Requested At')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_sent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='api.currency')),
                ('selected_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.bankaccount', verbose_name='Sent To Our Account')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
            ],
        ),
    ]
