# Generated by Django 6.0.3 on 2026-03-19 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Service Title')),
                ('icon_name', models.CharField(default='Zap', help_text='Lucide icon name', max_length=50, verbose_name='Icon Name')),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['priority', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='id_documents/', verbose_name='ID Document (Passport/National ID)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Is Verified Identity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
